### ISSUE TITLE
Trying to update some text but still getting a thread error

### ISSUE THREAD

**Issue by shealan** [ClaytonIndustries/TaskParallel#4]
I am trying to update some UI text from what I think is a background thread.

```
public class PusherManager : MonoBehaviour
{   
    private string text = "Loading...";
    public Text legacyText;

    async Task Start()
    {
        if (instance == null)
        {
            instance = this;
        }
        else if (instance != this)
        {
            Destroy(gameObject);
        }
        DontDestroyOnLoad(gameObject);
        await InitialisePusher();
        Console.WriteLine("Starting");
    }

    void Update()
    {
        legacyText.text = text;
    }

    private void PusherOnConnected(object sender)
    {
        Debug.Log("Connected");

        _channel.Bind("my-event", (PusherEvent eventData) =>
        {
            try {
                ChatMessage data = JsonConvert.DeserializeObject<ChatMessage>(eventData.Data);
                
                UnityTask.RunOnUIThread(() =>
                {
                    text = $"{data.Name} {data.Message}";
                });
            } catch (Exception e) {
                Debug.Log(e);
            }
        });
    }
}
```

I have removed some of the methods from my object but pasted enough here to give you an idea of what I am doing.

I'm getting this error:

```
UnityEngine.UnityException: Internal_CreateGameObject can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
```

**Comment by claytonone** [comment]
Hi @shealan, this is happening because UnityTask.RunOnUIThread is getting called for the first time from a background thread so when it tries to internally create the dispatcher to the UI thread it fails (as Unity stuff has to be done on the UI thread).

There's possibly 2 ways you could solve this, both of which cause the dispatcher to get created in the foreground.

1) Run a UnityTask.RunOnUIThread(() => {}) in your awake or start function that does nothing
2) Make a slight change to the Task Parallel code - In UnityTask.cs find the function "CreateDispatcherGameObject" and make it public instead of private. The in your awake or start function call UnityTask.CreateDispatcherGameObject()

**Comment by shealan** [comment]
Thank you! I went with option 2 as it seemed a little neater and works perfectly.
